<?php

$finder = PhpCsFixer\Finder::create()
    ->in([
        __DIR__ . '/app',
        __DIR__ . '/config',
        __DIR__ . '/database',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ])
    ->name('*.php')
    ->notName('*.blade.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

$config = new PhpCsFixer\Config();

return $config
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR12' => true,
        // Additional array and syntax rules
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'list_syntax' => ['syntax' => 'short'],
        // Operators and spacing
        'concat_space' => ['spacing' => 'one'],
        'no_mixed_echo_print' => ['use' => 'echo'],
        'unary_operator_spaces' => ['only_dec_inc' => false],
        // Constants and naming
        'constant_case' => ['case' => 'lower'],
        // String handling
        'single_quote' => true,
        'string_implicit_backslashes' => true,
        'string_line_ending' => true,
        'heredoc_to_nowdoc' => true,
        // PHPDoc rules
        'phpdoc_add_missing_param_annotation' => true,
        'phpdoc_align' => true,
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_line_span' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => true,
        'phpdoc_no_empty_return' => true,
        'phpdoc_no_package' => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order' => true,
        'phpdoc_order_by_value' => true,
        'phpdoc_param_order' => true,
        'phpdoc_return_self_reference' => true,
        'phpdoc_scalar' => true,
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_summary' => true,
        'phpdoc_tag_casing' => true,
        'phpdoc_tag_type' => true,
        'phpdoc_to_comment' => true,
        'phpdoc_to_param_type' => true,
        'phpdoc_to_return_type' => true,
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => true,
        'phpdoc_var_annotation_correct_order' => true,
        'phpdoc_var_without_name' => true,
        'no_superfluous_phpdoc_tags' => true,
        // PHPUnit rules
        'php_unit_construct' => true,
        'php_unit_dedicate_assert' => true,
        'php_unit_dedicate_assert_internal_type' => true,
        'php_unit_expectation' => true,
        'php_unit_fqcn_annotation' => true,
        'php_unit_mock' => true,
        'php_unit_mock_short_will_return' => true,
        'php_unit_namespaced' => true,
        'php_unit_no_expectation_annotation' => true,
        'php_unit_set_up_tear_down_visibility' => true,
        'php_unit_size_class' => true,
        'php_unit_strict' => true,
        'php_unit_test_annotation' => true,
        'php_unit_test_case_static_method_calls' => true,
        // Control structures and logic
        'no_alternative_syntax' => true,
        'no_superfluous_elseif' => true,
        'no_useless_else' => true,
        'simplified_if_return' => true,
        'simplified_null_return' => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_continue_to_break' => true,
        'trailing_comma_in_multiline' => true,
        // Class and property handling
        'single_class_element_per_statement' => true,
        'no_null_property_initialization' => true,
        'no_unset_on_property' => true,
        // Function and method handling
        'implode_call' => true,
        'lambda_not_used_import' => true,
        'method_argument_space' => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_sprintf' => true,
        'regular_callable_call' => true,
        'single_line_throw' => true,
        'void_return' => true,
        // Type declarations and casts
        'cast_spaces' => true,
        'lowercase_cast' => true,
        'modernize_types_casting' => true,
        'short_scalar_cast' => true,
        'type_declaration_spaces' => true,
        'types_spaces' => true,
        // Import and namespace handling
        'function_to_constant' => true,
        'global_namespace_import' => true,
        'native_constant_invocation' => true,
        'native_function_casing' => true,
        'native_function_invocation' => true,
        // Alias rules
        'ereg_to_preg' => true,
        'logical_operators' => true,
        'no_alias_functions' => true,
        'no_alias_language_construct_call' => true,
        'random_api_migration' => true,
        'set_type_to_cast' => true,
        // Risky transformations
        'dir_constant' => true,
        'fopen_flag_order' => true,
        'fopen_flags' => true,
        'is_null' => true,
        'long_to_shorthand_operator' => true,
        'modernize_types_casting' => true,
        'no_php4_constructor' => true,
        'no_unset_cast' => true,
        'psr_autoloading' => true,
        'return_assignment' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        // Other rules
        'blank_line_before_statement' => true,
        'escape_implicit_backslashes' => true,
        'explicit_indirect_variable' => true,
        'general_phpdoc_annotation_remove' => true,
        'general_phpdoc_tag_rename' => true,
        'heredoc_indentation' => true,
        'increment_style' => true,
        'integer_literal_case' => true,
        'linebreak_after_opening_tag' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'multiline_comment_opening_closing' => true,
        'multiline_whitespace_before_semicolons' => true,
        'no_binary_string' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'no_homoglyph_names' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_short_bool_cast' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_space_around_double_colon' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline' => true,
        'no_unneeded_braces' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unneeded_curly_braces' => true,
        'no_useless_nullsafe_operator' => true,
        'no_useless_return' => true,
        'no_whitespace_before_comma_in_array' => true,
        'non_printable_character' => true,
        'normalize_index_brace' => true,
        'octal_notation' => true,
        'operator_linebreak' => true,
        'ordered_interfaces' => true,
        'ordered_traits' => true,
        'self_static_accessor' => true,
        'semicolon_after_instruction' => true,
        'simple_to_complex_string_variable' => true,
        'single_line_comment_style' => true,
        'space_after_semicolon' => true,
        'spaces_inside_parentheses' => true,
        'statement_indentation' => true,
        'ternary_to_elvis_operator' => true,
        'ternary_to_null_coalescing' => true,
        'visibility_required' => true,
    ])
    ->setFinder($finder);
